### ISSUE TITLE
DateTime should always return a `datetime.datetime`

### ISSUE THREAD

**Issue by caseywebdev** [closeio/cleancat#45]
Currently, `DateTime` will return a `datetime.date` for ISO8601 dates like `2000-01-01` and a `datetime.datetime` for ISO8601 datetimes like `2000-01-01T00:00:00Z`. This is not expected behavior. `Date` should return a date, `DateTime` should return a datetime, and something like `Union(Date, Datetime)` should do what the current `DateTime` does.

**Comment by wojcikstefan** [comment]
I believe this is still an issue.

**Comment by mbdaryanto** [comment]
Can I try to fix this issue?

**Comment by AlecRosenbaum** [comment]
Sure, go for it.
